name: Python Generate

on:
  workflow_dispatch:
  schedule:
    - cron: '40 23 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: FirelightFlagboy/gh-runner-free-disk-space@main

      - name: Initialization environment
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq upgrade
          sudo -E apt-get -yqq autoremove
          sudo -E apt-get -yqq autoclean
          sudo -E apt-get -yqq clean
          sudo -E systemctl daemon-reload

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true

      - name: Install Requests
        run: |
          pip3 install tld
          pip3 install requests
          update-tld-names

      - name: Generate
        run: |
          mkdir -p dist
          chmod +x scripts/*.sh
          sh scripts/tv.sh
          sh scripts/gfwlist.sh -l -o dist/gfw1.txt
          curl -o- "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/tld-not-cn.txt" | sed 's/^\.//' | grep -vE "^#|^$" >> dist/gfw1.txt
          cat dist/gfw1.txt temp/gfw_wiki.txt temp/gfw_custom.txt | grep -vE '\.cn$|\.xn--fiqs8s$|\.baidu\.|\.hao123|\.iqiyi\.|\.sina\.|\.weibo\.|\.youku\.' | sed 's/\t/ /g' > dist/gfw2.txt
          grep -vE 'blogspot|discord|facebook|flickr|google|instagram|netflix|pinterest|porn|telegram|twitch|twitter|whatsapp|wikileaks|wikipedia|yahoo|youtube' dist/gfw2.txt > dist/gfw3.txt
          grep -vE '\.apple\.|\.icloud\.|\.itunes\.|\.microsoft\.|\.windows\.' dist/gfw3.txt | sed 's/ //g' | sed 's/\r/\n/g' | sort -uf | grep -v "^$" > dist/gfw.txt
          python3 ./scripts/build-adguard.py
          python3 ./scripts/build-apple.py
          python3 ./scripts/build-cnip.py
          python3 ./scripts/build-direct.py
          python3 ./scripts/build-proxy.py -f ./dist/gfw.txt
          python3 ./scripts/build-reject.py
          python3 ./scripts/build-telegram.py
          python3 ./scripts/build-tiktok.py
          python3 ./scripts/build-tracker.py
          sh scripts/update.sh
          python3 ./scripts/gen-final.py

      - name: Commit Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout main
          rm -rf dist
          git add .
          git commit -m "$(date '+%Y-%m-%d')"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 1
          gh_token: ${{secrets.GITHUB_TOKEN}}
